services:
  postgres:
    container_name: postgres-prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data

  redis:
    container_name: redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data_stage:/data

volumes:
  postgres_data_stage:
  redis_data_stage:

